# Generated by Django 5.1.3 on 2024-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('humidity', models.IntegerField()),
                ('temp', models.FloatField()),
                ('weather_desc', models.CharField(max_length=100)),
                ('clouds', models.CharField(max_length=100)),
                ('clouds_percent', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
